version: '3'

volumes:
  php_sockert:

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./volumes/html:/usr/share/nginx/html
      - ./volumes/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - php_sockert:/var/run
    depends_on:
      - php_fpm

  php_fpm:
    image: php:7.2-fpm
    volumes:
      - ./volumes/html:/usr/share/nginx/html
      - ./volumes/php_fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - php_sockert:/var/run
